### ISSUE TITLE
Custom Tileset not returning bounds

### ISSUE THREAD

**Issue by cirquelar** [developmentseed/morecantile#24]
I can't get xy bounds to return with my custom tile set:

```python
import rasterio, morecantile
from rasterio.crs import CRS

crs = CRS.from_proj4("+proj=stere +lat_0=90 +lon_0=0 +k=2 +x_0=0 +y_0=0 +R=3396190 +units=m +no_defs")
extent = [-13584760.000,-13585240.000,13585240.000,13584760.000]
tms = morecantile.TileMatrixSet.custom(extent, crs, identifier="MarsNPolek2MOLA5k”)

print(tms.matrix(0).dict(exclude_none=True))
> {'type': 'TileMatrixType', 'identifier': '0', 'scaleDenominator': 42195180871278.51, 'topLeftCorner': (-13584760.0, 13584760.0), 'tileWidth': 256, 'tileHeight': 256, 'matrixWidth': 1, 'matrixHeight': 1}

morecantile.tms.register(tms)
tms = morecantile.tms.get("MarsNPolek2MOLA5k")
assert "MarsNPolek2MOLA5k" in morecantile.tms.list()

tms.xy_bounds(morecantile.Tile(10,10,4))
ERROR 6: EPSG PCS/GCS code 0 not found in EPSG support files.  Is this a valid EPSG coordinate system?
Traceback (most recent call last):
  File "rasterio/_crs.pyx", line 363, in rasterio._crs._CRS.from_user_input
  File "rasterio/_err.pyx", line 194, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 7
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fcalef/miniconda3/envs/py37/lib/python3.7/site-packages/morecantile/models.py", line 290, in xy_bounds
    left, top = self._ul(*tile)
  File "/Users/fcalef/miniconda3/envs/py37/lib/python3.7/site-packages/morecantile/models.py", line 271, in _ul
    res = self._resolution(matrix)
  File "/Users/fcalef/miniconda3/envs/py37/lib/python3.7/site-packages/morecantile/models.py", line 192, in _resolution
    return matrix.scaleDenominator * 0.28e-3 / meters_per_unit(self.crs)
  File "/Users/fcalef/miniconda3/envs/py37/lib/python3.7/site-packages/morecantile/models.py", line 66, in crs
    return CRS.from_user_input(self.supportedCRS)
  File "/Users/fcalef/miniconda3/envs/py37/lib/python3.7/site-packages/rasterio/crs.py", line 459, in from_user_input
    obj._crs = _CRS.from_user_input(value, morph_from_esri_dialect=morph_from_esri_dialect)
  File "rasterio/_crs.pyx", line 367, in rasterio._crs._CRS.from_user_input
rasterio.errors.CRSError: The WKT could not be parsed. OGR Error code 7
```

It seems it doesn't like my custom non-Earth projection that doesn't have an EPSG code. Is there a way I can assign it a fake one? Do I need to modify local EPSG list?

**Comment by vincentsarago** [comment]
closing in favor of #23
