### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by hackartisan** [developmentseed/morecantile#83]
Hello, since the version bump to 3.1.0 we are getting the following output from pip. It seems like there's an issue with the package? Everything was fine under 3.0.5. Thanks for your help.

```
#!/bin/bash -eo pipefail
sudo pip3 install cogeo-mosaic
Collecting cogeo-mosaic
  Downloading cogeo-mosaic-4.0.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... - done
Collecting attrs
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 32.0 MB/s eta 0:00:00

Collecting cachetools
  Downloading cachetools-5.0.0-py3-none-any.whl (9.1 kB)
Collecting httpx
  Downloading httpx-0.22.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 KB 39.5 MB/s eta 0:00:00

Collecting mercantile
  Downloading mercantile-1.2.1-py3-none-any.whl (14 kB)
Collecting morecantile<4.0,>=3.0
  Downloading morecantile-3.1.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... - error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-e4svnxu4/morecantile_2e4a53c9883345079bf39a2a4ca2e893/setup.py", line 45, in <module>
          "morecantile=morecantile.scripts.cli:cli",
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 121, in setup
          dist.parse_config_files()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 705, in parse_config_files
          ignore_option_errors=ignore_option_errors)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 120, in parse_configuration
          meta.parse()
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 425, in parse
          section_parser_method(section_options)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 398, in parse_section
          self[name] = value
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 183, in __setitem__
          value = parser(value)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 513, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 348, in _parse_attr
          module = import_module(module_name)
        File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-install-e4svnxu4/morecantile_2e4a53c9883345079bf39a2a4ca2e893/morecantile/__init__.py", line 14, in <module>
          from .defaults import tms  # noqa
        File "/tmp/pip-install-e4svnxu4/morecantile_2e4a53c9883345079bf39a2a4ca2e893/morecantile/defaults.py", line 8, in <module>
          import attr
      ModuleNotFoundError: No module named 'attr'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


Exited with code exit status 1
```

**Comment by vincentsarago** [comment]
this issue seems to be with cogeo-mosaic, can you confirm by just doing `pip install morecantile`?

**Comment by hackartisan** [comment]
Hi thanks for looking. I get this error when I install morecantile directly.

```
$ sudo pip3 install morecantile
Collecting morecantile
  Using cached morecantile-3.1.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3_ymq0o7/morecantile_54c55e394b5b46629d46870ffc481e94/setup.py", line 45, in <module>
          "morecantile=morecantile.scripts.cli:cli",
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 121, in setup
          dist.parse_config_files()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 705, in parse_config_files
          ignore_option_errors=ignore_option_errors)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 120, in parse_configuration
          meta.parse()
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 425, in parse
          section_parser_method(section_options)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 398, in parse_section
          self[name] = value
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 183, in __setitem__
          value = parser(value)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 513, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 348, in _parse_attr
          module = import_module(module_name)
        File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-install-3_ymq0o7/morecantile_54c55e394b5b46629d46870ffc481e94/morecantile/__init__.py", line 14, in <module>
          from .defaults import tms  # noqa
        File "/tmp/pip-install-3_ymq0o7/morecantile_54c55e394b5b46629d46870ffc481e94/morecantile/defaults.py", line 8, in <module>
          import attr
      ModuleNotFoundError: No module named 'attr'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I get the same error when I use `--no-cache-dir` as well.

**Comment by hackartisan** [comment]
installing morecantile 3.0.5 works fine, so it's something to do with this release.

**Comment by vincentsarago** [comment]
@hackartisan can you check if your `pip` version is up to date? 
also what's the python version and the os?

**Comment by hackartisan** [comment]
Hi @vincentsarago, the pip / python version is:

```
$ pip3 --version
pip 22.0.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

The OS is Debian 10. It's a circleci docker image, configured here https://github.com/pulibrary/figgy/blob/412d78be4c82a9cb2e1de2cc0584117e71652071/.circleci/config.yml#L7

Thank you!

**Comment by hackartisan** [comment]
The setup script runs the pip update. When I do this manually on the box it says it's up to date:

```
$ sudo pip3 install pip -U
Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (22.0.3)
```

**Comment by vincentsarago** [comment]
this is likely an issue with the python/pipsetuptool version

as per https://packaging.python.org/en/latest/guides/single-sourcing-package-version/#single-sourcing-the-package-version

make sure you have `setuptools>=46.4.0`.

**Comment by vincentsarago** [comment]
confirmed in https://github.com/cogeotiff/rio-cogeo/issues/228#issuecomment-1048049588, this is happening when setuptool is out of date 

cc @hackartisan

**Comment by hackartisan** [comment]
👍🏻 thank you very much @vincentsarago!

**Comment by dahmanAl9r** [comment]
i got this problem when i tried to install autopy liberary....please...can anyone help me?
**Defaulting to user installation because normal site-packages is not writeable
Collecting autopy
  Using cached autopy-4.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for autopy, since package 'wheel' is not installed.
Installing collected packages: autopy
  Running setup.py install for autopy ... error
  error: subprocess-exited-with-error

  × Running setup.py install for autopy did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running install
      C:\Users\bahman\AppData\Roaming\Python\Python310\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated
. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\autopy
      copying autopy\__init__.py -> build\lib.win-amd64-cpython-310\autopy
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing fr
om the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during inst
allation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> autopy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

C:\Program Files\Python310>**

**Comment by vincentsarago** [comment]
👋 @dahmanAl9r This has nothing to do with the morecantile package. Please see https://github.com/autopilot-rs/autopy/#installation
